title: 外叔里嫩
author: ihuche
subtitle: My records of my life, my work, and others.

url: "https://rahul-bothra.github.io"
baseurl: "/parchment"

footer_only_homepage: true
footer_url: "https://github.com/rahul-bothra"
footer_text: "Theme by rahul-bothra"

profile-picture: assets/profile.png
favicon_location: assets/favicon.ico

permalink: /:year-:month-:day-:title/
sass:
    style: compressed
    sass_dir: css

timezone: Asia/Shanghai

navbar:
 - name: "About"
   link: "about"
 - name: "Resume"
   absolute-link: "https://rahul-bothra.github.io/CV.pdf"
